config/routes.rb
NestaBookshare::Application.routes.draw do

  

  resources :authors
  resources :bans
  resources :books #, only: [:destroy, :index]
  resources :loans
  resources :subjects
  resources :titles
  resources :watchings
  
  resource :account, :controller => :users
    
  resources :users do
    member do
      put :promote
      put :demote
      put :unban
    end
  end
  
  root :to => 'pages#home'
  
  resources :user_sessions
  resources :password_resets
  resources :messages

  get 'watchlist' => "users#watched_books"
  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register
  get 'members/:login' => "members#show"
  get 'lent' => 'users#loans', :as => :lent
  get 'borrowed' => 'users#borrowings', :as => :borrowings
  get 'search' => 'search#index', :as => :search
  
  get 'accessibility' => 'pages#accessibility', :as => :accessibility
  get 'contact' => 'pages#contact', :as => :contact
  

  get ':controller(/:action(/:id(.:format)))'
end

app/views/member_message/book_request.html.haml
%p
  = link_to image_tag(@sender.gravatar_image_url(80), :alt => @sender.login), url_for( :controller => :members, :action => :show, :login => @sender.login, :only_path => false )

%p
  = image_tag(@book.title.image_url)
  
%p
  = link_to @sender.login, url_for( :controller => :members, :action => :show, :login => @sender.login, :only_path => false )
  at 
  = CONFIG[:sitename]
  would like to borrow
  = link_to @book.title.title, title_url(@book.title)
  by
  = link_to @book.title.authors.first.name, author_url(@book.title.authors.first)

%p
  This book
  - if @book.status == StaticData::BOOK_STATUS['AVAILABLE']
    is currently available.
  - elsif @book.status == StaticData::BOOK_STATUS['ONLOAN']
    is currently on loan.
  - else
    is
    = @book.status_text
    \.
  

  
%p
  Reply to
  = @sender.login
  in the usual way by clicking
  %strong
    Reply 
  in your email program.
  
%p
  When you've given your book to 
  %strong
    = @sender.login
  click this link to mark it as lent:
  = link_to "Lend a Book", url_for( :controller => :loans, :action => :new, :borrower_login => @sender.login, :book_id => @book.id, :only_path => false)
  
%p
  This is not an official email from 
  = CONFIG[:sitename]
  staff.
  
%hr

=simple_format h @message
  
  

app/views/member_message/member_message.html.haml
%p
  = link_to image_tag(@sender.gravatar_image_url(80), :alt => @sender.login), url_for( :controller => :members, :action => :show, :login => @sender.login, :only_path => false )
  
%p
  This is a message from
  = link_to @sender.login, url_for( :controller => :members, :action => :show, :login => @sender.login, :only_path => false )
  at 
  = CONFIG[:sitename]
  
%p
  Reply to
  = @sender.login
  in the usual way by clicking
  %strong
    Reply 
  in your email program.
  
%p
  This is not an official email from 
  = CONFIG[:sitename]
  staff.
  
%hr

=simple_format h @message
  
  

app/views/member_message/password_reset_instructions.html.haml
%h2 Resetting your password

%p To reset your password, please click this link:

= link_to @edit_password_reset_url, @edit_password_reset_url

%p If you didn't ask us to reset your password just ignore this email.

app/views/member_message/password_reset_instructions.text.haml
Resetting your password


To reset your password, please click the link below or copy and paste it into your web browser:


= @edit_password_reset_url


If you didn't ask us to reset your password just ignore this email.

app/views/member_message/registration_confirmation.html.haml
%h2
  Welcome to 
  = CONFIG[:sitename]
  
%p Thanks for signing up. You're already logged in and ready to get started.

%h3 Getting Started

%ul
  %li
    Add some books you'd like to lend to your
    = link_to "My Books", books_url
    page.
  %li
    Let your friends and colleagues know about your books by sending them the link to your public books page:
    = link_to url_for(:controller => 'members', :action => :show, :login =>@recipient.login, :only_path => false), url_for(:controller => 'members', :action => :show, :login => @recipient.login, :only_path => false)
    
%h3 Tips

%ul
  %li
    You can borrow as many books as you like as long as the owners are happy to lend them to you.
  %li
    If someone requests a book from you, you don't have to lend it if you don't want to.
  %li
    You can lend a book for a minimum of one week. There's no maximum.
  %li
    Need help? Got a comment or complaint? 
    = link_to "Get in touch.", url_for(:controller => :pages, :action => :contact, :only_path => false)
  - unless CONFIG[:twitter].nil?
    %li
      Are you on Twitter? Follow 
      %a{ :href => "http://twitter.com/#{CONFIG[:twitter]}" }<
        = "@#{CONFIG[:twitter]}"
      for new book alerts.
    
%hr

%p
  Your username is
  %strong
    = @recipient.login
  and you can login at
  = link_to url_for(login_url), login_url
    