config/routes.rb
NestaBookshare::Application.routes.draw do

  

  resources :authors
  resources :bans
  resources :books #, only: [:destroy, :index]
  resources :loans
  resources :subjects
  resources :titles
  resources :watchings
  
  resource :account, :controller => :users
    
  resources :users do
    member do
      put :promote
      put :demote
      put :unban
    end
  end
  
  root :to => 'pages#home'
  
  resources :user_sessions
  resources :password_resets
  resources :messages

  get 'watchlist' => "users#watched_books"
  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register
  get 'members/:login' => "members#show"
  get 'lent' => 'users#loans', :as => :lent
  get 'borrowed' => 'users#borrowings', :as => :borrowings
  get 'search' => 'search#index', :as => :search
  
  get 'accessibility' => 'pages#accessibility', :as => :accessibility
  get 'contact' => 'pages#contact', :as => :contact
  

  get ':controller(/:action(/:id(.:format)))'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :titles
  
  validates_length_of :name, :in => 2..255, :too_long => 'pick a shorter name', :too_short => 'pick a longer name'
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all(:order => :name)
  end

  # GET /subjects/1
  # GET /subjects/1.xml
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subject }
      format.json { render :json => @subject }
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.haml
%h1= @page_title = "Subjects"


- for subject in @subjects
  %p
    = link_to subject.name, subject

app/views/subjects/show.html.haml
%h1= @page_title = @subject.name

- if @subject.titles.count > 0  
  %table    
    - for title in @subject.titles
      %tr
        %td= link_to(image_tag(title.image_url), title_path(title))
        %td
          %span.book_list_title
            = link_to title.title, title_path(title)
          - unless title.subtitle.nil?
            %br
            = title.subtitle
          %br
          %br
          = link_to title.authors.first.name, author_path(title.authors.first)
- else
  %p There are no books for this subject.