config/routes.rb
NestaBookshare::Application.routes.draw do

  

  resources :authors
  resources :bans
  resources :books #, only: [:destroy, :index]
  resources :loans
  resources :subjects
  resources :titles
  resources :watchings
  
  resource :account, :controller => :users
    
  resources :users do
    member do
      put :promote
      put :demote
      put :unban
    end
  end
  
  root :to => 'pages#home'
  
  resources :user_sessions
  resources :password_resets
  resources :messages

  get 'watchlist' => "users#watched_books"
  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register
  get 'members/:login' => "members#show"
  get 'lent' => 'users#loans', :as => :lent
  get 'borrowed' => 'users#borrowings', :as => :borrowings
  get 'search' => 'search#index', :as => :search
  
  get 'accessibility' => 'pages#accessibility', :as => :accessibility
  get 'contact' => 'pages#contact', :as => :contact
  

  get ':controller(/:action(/:id(.:format)))'
end

app/models/title.rb
require 'json/pure'

class Title < ActiveRecord::Base
  has_and_belongs_to_many :subjects
  has_and_belongs_to_many :authors
  has_many :books
  
  validates_length_of :title, :minimum => 1
  validates_associated :authors
  #ToDo: comento validates_isbn porque da errores al desplegar en heroku.
  #validates_isbn :isbn13, :with => :isbn13
  
  index do
    title
    subtitle
    description
  end
  
  def to_param
    isbn13
  end
  
  def isbn10
    # http://rubygems.org/gems/isbn
    ISBN.ten(isbn13)
  end
  
  def title_and_author
    "#{self.title} by #{self.authors.first.name}"
  end
  
  def self.find_or_create_by_isbn13(isbn13)
    
    isbn13.strip!
    
    # Is this a barcode scanned by an unmodified Cuecat reader?
    if isbn13.size == 50
      code = CueCat.new(isbn13[1..50])
      isbn13 = code.value.to_s
    end
    
    t2 = self.find_by_isbn13(isbn13)
    
    unless t2.nil?
      return t2
    end

    # Look up in Google Books API
    t = Title.new
    
    url = "https://www.googleapis.com/books/v1/volumes/?q=%s" % isbn13
    http = HTTPClient.new
    res = http.get(url)
    data = JSON.parse(res.body)

    found_item = nil

    # Loop through result set to find the item with our isbn13
    data['items'].each do |item|
      item['volumeInfo']['industryIdentifiers'].each do |isbn|
        if isbn['type'] == "ISBN_13" && isbn['identifier'] == isbn13
          found_item = item
        end
      end
      break if found_item
    end

    if found_item
      t.title = found_item['volumeInfo']['title']
      t.description = found_item['volumeInfo']['description']
      t.image_url = found_item['volumeInfo']['imageLinks']['smallThumbnail']

      unless found_item['volumeInfo']['authors'].nil?
        found_item['volumeInfo']['authors'].each do |author|
          if a = Author.find_by_name(author)
            t.authors << a
          else
            t.authors << Author.create(:name => author)
          end
        end
      end
        
      unless found_item['volumeInfo']['categories'].nil?
        found_item['volumeInfo']['categories'].each do |subject|
          if s = Subject.find_by_name(subject)
            t.subjects << s
          else
            t.subjects << Subject.create(:name => subject)
          end
        end
      end
        
      t.isbn13 = isbn13
      t.save
      return t
    else
      # We didn't find any item with this ISBN in the API
    end
  end
  
  # Update all titles from Google Books API
  def self.update
    i = 0
    j = Title.count
    Title.all.each do |t|
      i += 1
      puts "#{t.isbn13} (#{i} of #{j})"
      t.update_from_api!
      sleep 3
    end
  end
  
  def update_from_api!
    url = "https://www.googleapis.com/books/v1/volumes/?q=%s" % self.isbn13
    http = HTTPClient.new
    res = http.get(url)
    data = JSON.parse(res.body)

    found_item = nil

    # Loop through result set to find the item with our isbn13
    data['items'].each do |item|
      item['volumeInfo']['industryIdentifiers'].each do |isbn|
        if isbn['type'] == "ISBN_13" && isbn['identifier'] == isbn13
          found_item = item
        end
      end
      break if found_item
    end

    if found_item
      self.title = found_item['volumeInfo']['title']
      self.description = found_item['volumeInfo']['description']
      self.image_url = found_item['volumeInfo']['imageLinks']['smallThumbnail']

      # Authors
      self.authors = [] # Remove existing authors

      unless found_item['volumeInfo']['authors'].nil?
        found_item['volumeInfo']['authors'].each do |author|
          if a = Author.find_by_name(author)
            self.authors << a
          else
            self.authors << Author.create(:name => author)
          end
        end
      end
        
      # Subjects
      self.subjects = [] # Remove existing subjects
        
      unless found_item['volumeInfo']['categories'].nil?
        found_item['volumeInfo']['categories'].each do |subject|
          if s = Subject.find_by_name(subject)
            self.subjects << s
          else
            self.subjects << Subject.create(:name => subject)
          end
        end
      end
        
      self.save
    else
      # We didn't find any item with this ISBN in the API
    end
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    @titles = Title.all :order => 'created_at DESC'
    
    respond_to do |format|
      format.atom { render :layout => false } # index.atom.builder
      format.xml  { render :xml => @titles, :include => [:books, :subject, :authors] }
      format.json  { render :json => @titles, :include => [:books, :subject, :authors] }
    end
  end

  # GET /titles/1
  # GET /titles/1.xml
  # GET /titles/1.json
  def show
    @title = Title.find_by_isbn13(params[:id])
    @watching = Watching.new
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @title, :include => [:books, :subject, :authors] }
      format.json { render :json => @title, :include => [:books, :subject, :authors] }
    end
  end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/show.html.haml
- @page_title = @title.title_and_author

%span.left_col
  = image_tag @title.image_url, :height => 80, :alt => @title.title_and_author

.right_col
  %h1
    = @title.title
  %p
    = @title.subtitle
  %p
    - for author in @title.authors
      %br
      = link_to author.name, author_path(author)

  -# Google Book Search data contains HTML entities so use raw() to preserve them
  %div= raw @title.description
  
  - @title.subjects.each do |subject|
    %p
      = link_to subject.name, subject_path(subject)
  
  %p
    Search for this book at 
    %a{ :href => "http://www.anytown.gov.uk/library/search?isbn=" + @title.isbn10 }<
      Anytown Libraries 
    and 
    %a{ :href => "http://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=#{@title.isbn13}" }<
      Amazon



  - if @title.books.count > 0 

    %h2.top_spacer You can borrow this book from:
  
    %table    
      - for book in @title.books
        %tr
          %td
            = link_to (image_tag book.user.gravatar_image_url(50), :alt => book.user.login), :controller => :members, :action => :show, :login => book.user.login
            %br
            = link_to book.user.login, :controller => :members, :action => :show, :login => book.user.login

          %td
            - if book.status == StaticData::BOOK_STATUS['AVAILABLE']
              available
            - elsif book.status == StaticData::BOOK_STATUS['ONLOAN']
              on loan
            - else
              = book.status_text

          %td
            - if current_user

              - if current_user.owns?(book)
                You own this book
                
              - elsif current_user.watched?(book)
                Watched
                
              - else
                = form_for @watching do |f|
                  = hidden_field_tag :book_id, book.id
                  = f.submit "Watch Book"

            - else
              &nbsp;

          %td
            - if current_user && ! current_user.owns?(book) && (book.status == StaticData::BOOK_STATUS['AVAILABLE'] || book.status == StaticData::BOOK_STATUS['ONLOAN'])
              = link_to "Request Book", :controller => :messages, :action => :request_new, :book => book, :recipient => book.user.login

  - else               
    %p No member is currently offering this book.
    