config/routes.rb
NestaBookshare::Application.routes.draw do

  

  resources :authors
  resources :bans
  resources :books #, only: [:destroy, :index]
  resources :loans
  resources :subjects
  resources :titles
  resources :watchings
  
  resource :account, :controller => :users
    
  resources :users do
    member do
      put :promote
      put :demote
      put :unban
    end
  end
  
  root :to => 'pages#home'
  
  resources :user_sessions
  resources :password_resets
  resources :messages

  get 'watchlist' => "users#watched_books"
  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register
  get 'members/:login' => "members#show"
  get 'lent' => 'users#loans', :as => :lent
  get 'borrowed' => 'users#borrowings', :as => :borrowings
  get 'search' => 'search#index', :as => :search
  
  get 'accessibility' => 'pages#accessibility', :as => :accessibility
  get 'contact' => 'pages#contact', :as => :contact
  

  get ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.haml
!!!5
%html
  /
    NESTA Bookshare
  %head
    %title= 'LibreTeka'
    = stylesheet_link_tag "style"

    = csrf_meta_tag
    = yield :head

  %body
    #firstmenu
      #logolibr
        <IMG SRC="/images/logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

      #search
        = form_tag(search_path, :method => :get) do
          = text_field_tag :q, '', { :size => 25, :class => 'bigfield' }
          = submit_tag "Buscar Libro", { :class => 'bigfield' }
      
      
    #userbar
      = link_to_unless_current "Inicio", :root, :accesskey => '1'
      &nbsp;&nbsp;
      - if current_user
        Conectado como
        %strong
          = link_to current_user.login, :controller => :members, :action => :show, :login => current_user.login
        &nbsp;&nbsp;
        = link_to_unless_current "Mis libros (#{current_user.books.count.to_s})", books_path, :accesskey => '2'
        &nbsp;&nbsp;
        = link_to_unless_current "Has prestado (#{current_user.active_loans.count.to_s})", :lent, :accesskey => '3'
        &nbsp;&nbsp;
        = link_to_unless_current "Tienes prestados (#{current_user.active_borrowings.count.to_s})", :borrowings, :accesskey => '4'
        &nbsp;&nbsp;
        = link_to_unless_current "Lista de interés (#{current_user.watched_books.count.to_s})", :watchlist, :accesskey => '5'
        &nbsp;&nbsp;
        - if is_admin?
          = link_to_unless_current "Configuración", :controller => :admin
        &nbsp;&nbsp;
        = link_to_unless_current "Log Out", :logout, :method => :delete, :confirm => "Are you sure you want to logout?"
      - else
        = link_to_unless_current "Regístrate", :register
        &nbsp;&nbsp;
        = link_to_unless_current "Inicio de sesión", :login
    
    #main
      
      - if flash.notice
        .notice= flash.notice
      - if flash.alert
        .notice.alert= flash.alert
  
      = yield
    
    #footer
      %a{ :href => "http://www.stsi-madrid.org/", :title => "STSI" }
        Desarrollado por el STSI. 
      &nbsp;&nbsp;
      %a{ :href => "https://github.com/pocasluces/LibreTeka-from-BookShare", :title => "Ir a github" }
        Código abierto y libre.
      &nbsp;&nbsp;

app/views/layouts/member_message.html.haml
!!!5
%html
  %head
    :css
      body
      {
        font-family: Helvetica, Arial, sans-serif;
      }
      
      h1
      {  
        color: #d12349;
        font-size: 250%;
      }
      
      img
      {
        border: 0;
      }

  %body
  
    %h1
      = CONFIG[:sitename]
    
    = yield